### ISSUE TITLE
Ignored subdivision

### ISSUE THREAD

**Issue by MrGitGo** [cartographer-project/cartographer_ros#1326]
I have set up google cartographer many times for 2d and 3d. But now I wanted to use a rgbd camera for 2d mapping. In order to do this I converted the point cloud to laserscan, with this package: http://wiki.ros.org/pointcloud_to_laserscan

I use a pico monstar.

When I launch google cartographer with the pc_to_laserscan I get this warning:

`[ WARN] [1560845643.823460226]: W0618 10:14:03.000000 18489 sensor_bridge.cc:200] Ignored subdivision of a LaserScan message from sensor scan because previous subdivision time 636964424437691470 is not before current subdivision time 636964424437691470`

This is the header of /scan:
```
  seq: 100
  stamp: 
    secs: 1560845618
    nsecs: 155853000
  frame_id: "royale_camera_optical_frame"
angle_min: -3.1400001049
angle_max: 3.1400001049
angle_increment: 0.00870000012219
time_increment: 0.0
scan_time: 0.333299994469
range_min: 0.449999988079
range_max: 10.0
ranges: [inf, inf, inf, 0.45439407229423523, 0.45167145133018494, inf, inf,
```
