### ISSUE TITLE
Error after activate `TRAJECTORY_BUILDER_2D.use_imu_data` for IMU integration

### ISSUE THREAD

**Issue by ywiyogo** [cartographer-project/cartographer_ros#1565]
I'm trying to integrate my LSM9D61 IMU sensor which is mounted under the Lidar sensor. I publish the topic to `/imu` and get such a result:

```
header: 
  seq: 143
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "imu_link"
orientation: 
  x: 0.052366103977
  y: 0.0604441389441
  z: -0.490040838718
  w: 0.86802315712
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.0036357101053
  y: 0.0145206972957
  z: -0.0011967997998
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: -6.94155586604e-05
  y: -7.89901184756e-05
  z: 0.00998626548529
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

My urdf joint is like this:

```  
   <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.01 0.008 0.004" />
      </geometry>
      <material name="orange" />
    </visual>
  </link>


  <joint name="imu_link_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_link" />
    <origin xyz="0 0 0" />
  </joint>

  <joint name="laser_link_joint" type="fixed">
    <parent link="base_link" />
    <child link="laser" />
    <origin xyz="0.0 0 0.03" />
  </joint>
```
Then the lua configuration is changed like these line:

```
options = {
  map_frame = "map",
  tracking_frame = "imu_link",
  published_frame = "base_link",
  odom_frame = "odom",
  publish_frame_projected_to_2d = true,
  imu_sampling_ratio = 1.,
  ...
}
TRAJECTORY_BUILDER_2D.use_imu_data = true
```

After I start the roslaunch, I got such a warning that prevent the cartographer_ros to work smoothly:
```
[ INFO] [1605877770.851944410]: World frame: map 
[ INFO] [1605877770.852029539]: Lidar frame: base_link 
[ INFO] [1605877770.963107558]: I1120 14:09:30.000000 21220 ordered_multi_queue.cc:172] All sensor data for trajectory 0 is available starting at '637414745709617497'.
[ WARN] [1605877814.332847680]: W1120 14:10:14.000000 21220 ordered_multi_queue.cc:155] Queue waiting for data: (0, imu)
[ WARN] [1605877817.107229400]: W1120 14:10:17.000000 21220 ordered_multi_queue.cc:155] Queue waiting for data: (0, imu)
```

The warnings appears repeatly each 3 secs. If I set `TRAJECTORY_BUILDER_2D.use_imu_data` to false, the cartographer_ros works normally.
What's wrong with my configuration?
